; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Add top-level config to include paths
build_flags = -I${project_dir}/../config

; Thư viện OneWire + DallasTemperature
lib_deps =
  PaulStoffregen/OneWire
  milesburton/DallasTemperature
  knolleary/PubSubClient
